name: Build Scikit-learn for Windows 32-bit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: [3.9.13]  # Specify the Python version you want to use
        architecture: [32]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel joblib threadpoolctl
        pip install cython numpy==1.24.4 scipy==1.9.1# Install Cython if required by Scikit-learn

    - name: Build Scikit-learn
      run: |
        pip install --no-build-isolation --no-use-pep517 scikit-learn  # Install Scikit-learn from source

    - name: Test Scikit-learn
      run: |
        python -c "import sklearn; print(sklearn.__version__)"

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: scikit-learn-build
        path: ./dist
